### PR TITLE
reworked for performance and more entities

### PR DESCRIPTION
**Pull request by maciejhirsz**

### CODE REVIEW

**Comment by maciejhirsz** [comment]
Lemme know if anything is unclear, your project comes up pretty high in npm search, would be nice if it was sleek :)

**Comment by rob204** [comment]
May I note a few obvious pros and cons?

### Pros
- more performant because e.g. it doesn't construct and run a new RegExp for each entity name each time it gets called
- 50% more entities covered
- attempts to work case-insensitive (i flag on the regular expression)
- non-iterative replacing ("&amp;lt;" becomes "&lt;" instead of "<")

### Cons
- matches property names from Object prototype ("&toString;" becomes "function toString() { [native code] }")
- fails at working case-insensitive (no toLowerCase in replace callback)

**Comment by maciejhirsz** [comment]
@rob204 Thanks, fixed both issues, even though this is a _very_ stale PR by now :p.

**Comment by andineck** [comment]
@maciejhirsz @rob204 thank you very much for your contribution! And at the same time I want to apologize for my unresponsiveness. I was just too caught up in my day job and other projects.

If you could do the same transformations & improvements to https://github.com/intesso/encode-html that would be great, so that if you call `decode(encode(input))` it gives back the original input.

I promise I will merge it immediately :-)

**Pull request merged**
